"""Registered formulas: 概率论与随机过程 第二章 随机变量及其分布."""

from core.pdf_content_v2.formula_registry.formula_card import RegFormulaCard

COURSE = "probability_ch2"
CHAPTER = "ch2"

PROBABILITY_CH2_FORMULAS: list[RegFormulaCard] = [
    RegFormulaCard(
        formula_id="prob_ch2_rv_definition",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="random_variable",
        title="随机变量定义",
        display_formula="X: Ω → R",
        typst_formula="$X: Omega -> RR$",
        plain_text="随机变量是样本空间到实数的映射，对任意实数x，{X≤x}是事件",
        conditions=["对任意实数 x，{X ≤ x} 为事件", "样本空间可测"],
        common_variants=["X(ω) 表示样本点 ω 对应的实数"],
        common_mistakes=["混淆随机变量与普通变量", "认为随机变量就是概率"],
        source_refs=["概率论与随机过程 §2.1"],
        source_level="textbook", exam_priority="★★★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_cdf_definition",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="distribution_function",
        title="分布函数",
        display_formula="F(x) = P{X ≤ x}",
        typst_formula="$F(x) = P\\{X <= x\\}$",
        plain_text="分布函数是随机变量X不超过x的累积概率",
        conditions=["F(x) 单调不减", "F(x) 右连续", "F(-∞)=0", "F(+∞)=1"],
        common_variants=["P{a<X≤b} = F(b)-F(a)", "P{X>b} = 1-F(b)"],
        common_mistakes=["忘记验证三条性质就判定分布函数", "混淆 P{X<x} 和 P{X≤x}", "分段函数的分段点处理错误"],
        source_refs=["概率论与随机过程 §2.2"],
        source_level="textbook", exam_priority="★★★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_pmf_definition",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="discrete_random_variable",
        title="离散型随机变量分布律",
        display_formula="P{X = x_i} = p_i,  i = 1,2,...",
        typst_formula="$P\\{X = x_i\\} = p_i, quad i = 1,2,dots$",
        plain_text="离散型随机变量每个取值的概率",
        conditions=["p_i ≥ 0", "∑ p_i = 1"],
        common_variants=["分布律可列成表格形式"],
        common_mistakes=["概率和不为 1", "遗漏某些取值", "分布函数在取值点不左连续"],
        source_refs=["概率论与随机过程 §2.3"],
        source_level="textbook", exam_priority="★★★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_pdf_definition",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="continuous_random_variable",
        title="连续型随机变量密度函数",
        display_formula="F(x) = ∫_{-∞}^{x} f(t)dt",
        typst_formula="$F(x) = integral_(-oo)^x f(t) dif t$",
        plain_text="分布函数是密度函数从负无穷到x的积分",
        conditions=["f(x) ≥ 0", "∫_{-∞}^{∞} f(x)dx = 1", "P{X=a} = 0（单点概率为零）"],
        common_variants=["P{a<X≤b} = ∫_a^b f(x)dx"],
        common_mistakes=["把密度值 f(a) 当作概率 P{X=a}", "归一化常数算错", "分段积分漏写区间条件"],
        source_refs=["概率论与随机过程 §2.4"],
        source_level="textbook", exam_priority="★★★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_bernoulli",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="bernoulli",
        title="0-1 分布",
        display_formula="P{X=1}=p, P{X=0}=1-p",
        typst_formula="$P\\{X=1\\}=p, quad P\\{X=0\\}=1-p$",
        plain_text="一次伯努利试验成功或失败的概率",
        conditions=["只有两个可能结果", "0 < p < 1"],
        common_variants=["E(X)=p", "D(X)=p(1-p)"],
        common_mistakes=["混淆 p 和 1-p", "误把伯努利当作二项"],
        source_refs=["概率论与随机过程 §2.5"],
        source_level="textbook", exam_priority="★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_binomial",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="binomial",
        title="二项分布",
        display_formula="P{X=k} = C(n,k) p^k (1-p)^{n-k}",
        typst_formula="$P\\{X=k\\} = C_n^k p^k (1-p)^(n-k)$",
        plain_text="n次独立重复伯努利试验中成功k次的概率",
        conditions=["n 次独立重复试验", "每次成功概率为 p", "k = 0,1,...,n"],
        common_variants=["E(X)=np", "D(X)=np(1-p)"],
        common_mistakes=["不要漏 C(n,k) 组合数", "不要把二项分布和超几何分布混淆", "p 和 1-p 不要弄反"],
        source_refs=["概率论与随机过程 §2.5"],
        source_level="textbook", exam_priority="★★★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_poisson",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="poisson",
        title="泊松分布",
        display_formula="P{X=k} = e^{-λ} λ^k / k!",
        typst_formula="$P\\{X=k\\} = e^(-lambda) lambda^k \\/ k!$",
        plain_text="单位时间内随机事件发生k次的概率",
        conditions=["λ > 0", "k = 0,1,2,..."],
        common_variants=["E(X)=λ", "D(X)=λ", "二项近似: λ=np (n大p小)"],
        common_mistakes=["λ 和 n,p 关系弄错", "忘记 e^{-λ} 项", "近似条件不满足时强行使用"],
        source_refs=["概率论与随机过程 §2.5"],
        source_level="textbook", exam_priority="★★★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_geometric",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="geometric",
        title="几何分布",
        display_formula="P{X=k} = (1-p)^{k-1} p",
        typst_formula="$P\\{X=k\\} = (1-p)^(k-1) p$",
        plain_text="首次成功发生在第k次试验的概率",
        conditions=["k = 1,2,...", "0 < p < 1", "每次试验独立"],
        common_variants=["E(X)=1/p", "D(X)=(1-p)/p²"],
        common_mistakes=["与二项分布混淆（几何是首次成功）", "指数从 k-1 还是 k 出错"],
        source_refs=["概率论与随机过程 §2.5"],
        source_level="textbook", exam_priority="★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_hypergeometric",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="hypergeometric",
        title="超几何分布",
        display_formula="P{X=k} = C(M,k)C(N-M,n-k) / C(N,n)",
        typst_formula="$P\\{X=k\\} = C_M^k C_(N-M)^(n-k) \\/ C_N^n$",
        plain_text="不放回抽样中抽到k个指定类型物品的概率",
        conditions=["不放回抽样", "N 为总体大小，M 为成功品数", "抽取 n 件"],
        common_variants=["当 N 很大时近似二项分布"],
        common_mistakes=["与二项分布混淆（不放回 vs 放回）", "组合数下标混淆"],
        source_refs=["概率论与随机过程 §2.5"],
        source_level="textbook", exam_priority="★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_uniform",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="uniform",
        title="均匀分布",
        display_formula="f(x) = 1/(b-a),  a < x < b",
        typst_formula="$f(x) = 1\\/(b-a), quad a < x < b$",
        plain_text="在区间(a,b)内等可能取值",
        conditions=["a < b", "区间外密度为 0"],
        common_variants=["E(X)=(a+b)/2", "D(X)=(b-a)²/12"],
        common_mistakes=["忘记区间外为 0", "方差公式分母记错"],
        source_refs=["概率论与随机过程 §2.6"],
        source_level="textbook", exam_priority="★★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_exponential",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="exponential",
        title="指数分布",
        display_formula="f(x) = λe^{-λx},  x > 0",
        typst_formula="$f(x) = lambda e^(-lambda x), quad x > 0$",
        plain_text="描述等待时间的分布，具有无记忆性",
        conditions=["λ > 0", "x > 0 时密度如上，x ≤ 0 时为 0"],
        common_variants=["F(x)=1-e^{-λx}", "E(X)=1/λ", "D(X)=1/λ²", "无记忆性: P{X>s+t|X>s}=P{X>t}"],
        common_mistakes=["参数混淆 λ 和 1/λ（均值是 1/λ）", "忘记 x>0 的定义域"],
        source_refs=["概率论与随机过程 §2.6"],
        source_level="textbook", exam_priority="★★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_normal",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="normal",
        title="正态分布",
        display_formula="X ~ N(μ, σ²)",
        typst_formula="$X ~ N(mu, sigma^2)$",
        plain_text="自然界最常见的连续分布，中心极限定理的基础",
        conditions=["σ > 0", "标准化: Z = (X-μ)/σ ~ N(0,1)"],
        common_variants=[
            "密度: f(x) = exp(-(x-μ)²/(2σ²)) / (σ√(2π))",
            "E(X)=μ", "D(X)=σ²",
            "查表: Φ(-z) = 1-Φ(z)",
        ],
        common_mistakes=["忘记标准化变换（减均值除标准差）", "混淆 σ 和 σ²", "Φ(-z) 转 1-Φ(z) 错误"],
        source_refs=["概率论与随机过程 §2.6"],
        source_level="textbook", exam_priority="★★★★★",
    ),
    RegFormulaCard(
        formula_id="prob_ch2_rv_transform",
        course_id=COURSE, chapter_id=CHAPTER, concept_id="rv_function_distribution",
        title="随机变量函数的分布",
        display_formula="F_Y(y) = P{Y≤y} = P{g(X)≤y}",
        typst_formula="$F_Y(y) = P\\{Y<=y\\} = P\\{g(X)<=y\\}$",
        plain_text="已知X分布求Y=g(X)分布，通用方法为分布函数法",
        conditions=["g 为 Borel 可测函数", "单调时可用公式: f_Y(y)=f_X(h(y))|h'(y)|"],
        common_variants=["线性变换 Y=aX+b → f_Y(y)=f_X((y-b)/a)/|a|", "非单调需分区讨论"],
        common_mistakes=["非单调不分区直接套公式", "漏掉绝对值 |h'(y)|", "忘记反函数定义域"],
        source_refs=["概率论与随机过程 §2.7"],
        source_level="textbook", exam_priority="★★★★★",
    ),
]
